FROM oven/bun:latest

WORKDIR /app


COPY ./packages ./packages
COPY /package.json /package.json
COPY /bun.lock /bun.lock
COPY /turbo.json  /turbo.json

COPY /apps/backend /app/backend

COPY . .

RUN bun install


EXPOSE 3001

CMD [ "bun","run","start:backend" ]
