FROM oven/bun:latest

WORKDIR /app
ARG MONGO_URL
COPY ./packages ./packages
COPY /package.json /package.json
COPY /bun.lock /bun.lock
COPY /turbo.json  /turbo.json

COPY /apps/web /app/web

COPY . .

RUN bun install
RUN bun run build 

ENV DATABASE_URL =${MONGO_URL}
EXPOSE 3000

CMD [ "bun","run","start:web" ]
